version: '3'

services:
  app:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/models/5432; do sleep 1; done; python3 -m app'
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
